import type { Shipment } from "@shared/schema";
import { geoLookup } from "./geo";
import { getDriverMap } from "./fleet";

export function parseCsvRow(line: string, delim: string = ","): string[] {
  const cells: string[] = [];
  let cur = "";
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQ && i + 1 < line.length && line[i + 1] === '"') { cur += '"'; i++; }
      else { inQ = !inQ; }
    } else if (ch === delim && !inQ) {
      cells.push(cur.trim());
      cur = "";
    } else {
      cur += ch;
    }
  }
  cells.push(cur.trim());
  return cells;
}

// ShipLogic normally exports comma-separated, but a CSV re-saved through Excel
// or a locale that uses semicolons (or a tab/pipe export) would otherwise
// collapse every row into a single cell — leaving every column empty and the
// preview full of fallback waybills. Pick whichever delimiter splits the header
// line into the most fields; comma wins ties so existing files are unaffected.
export function detectDelimiter(line: string): string {
  const candidates = [",", ";", "\t", "|"];
  let best = ",";
  let bestCount = parseCsvRow(line, ",").length;
  for (const d of candidates) {
    if (d === ",") continue;
    const count = parseCsvRow(line, d).length;
    if (count > bestCount) { bestCount = count; best = d; }
  }
  return best;
}

export interface ParseResult {
  ships: Shipment[];
  warnings: string[];
  raw: string[][];
  headers: string[];
  accountCodes: { code: string; name: string }[];
}

export function parseShipLogicCSV(text: string, clientMap?: Record<string, string>): ParseResult {
  const lines = text.split(/\r?\n/).filter((l) => l.trim());
  if (lines.length < 2) return { ships: [], warnings: [], raw: [], headers: [], accountCodes: [] };

  let hdrIdx = 0;
  if (lines[0].toLowerCase().indexOf("generated by") >= 0) {
    hdrIdx = 1;
  } else if (parseCsvRow(lines[0], detectDelimiter(lines[0])).length < 10 && lines.length > 1) {
    hdrIdx = 1;
  }
  if (hdrIdx >= lines.length) return { ships: [], warnings: [], raw: [], headers: [], accountCodes: [] };

  const delim = detectDelimiter(lines[hdrIdx]);
  const hdr = parseCsvRow(lines[hdrIdx], delim);
  const ci: Record<string, number> = {};
  hdr.forEach((h, i) => { ci[h.toLowerCase().trim()] = i; });

  function g(row: string[], name: string): string {
    const idx = ci[name.toLowerCase()];
    return idx != null && row[idx] != null ? row[idx].trim() : "";
  }

  function gNum(row: string[], ...names: string[]): number | null {
    for (const name of names) {
      const idx = ci[name.toLowerCase()];
      if (idx != null && row[idx] != null) {
        const v = parseFloat(row[idx].trim());
        if (!isNaN(v) && v !== 0) return v;
      }
    }
    return null;
  }

  function isValidSACoord(lat: number | null, lng: number | null): boolean {
    if (lat === null || lng === null) return false;
    return lat >= -35 && lat <= -22 && lng >= 16 && lng <= 33;
  }

  const ships: Shipment[] = [];
  const warnings: string[] = [];
  const raw: string[][] = [];
  const seenAccounts = new Map<string, string>();

  const wbMap = new Map<string, { shipIdx: number; parcelCount: number }>();

  for (let r = hdrIdx + 1; r < lines.length; r++) {
    if (!lines[r].trim()) continue;
    const row = parseCsvRow(lines[r], delim);
    raw.push(row);

    const wb = g(row, "short waybill number") || g(row, "custom waybill number") || ("IMP" + String(r).padStart(3, "0"));
    const parcelType = g(row, "package type") || g(row, "parcel type") || "";
    const parcelCategory = g(row, "parcel category") || g(row, "parcel_category") || "";

    const existing = wbMap.get(wb);
    if (existing) {
      existing.parcelCount++;
      const ship = ships[existing.shipIdx];
      if (parcelType && !ship.parcelType) ship.parcelType = parcelType;
      if (parcelCategory && !ship.parcelCategory) ship.parcelCategory = parcelCategory;
      continue;
    }

    const accCode = g(row, "account code");
    const rawClient = g(row, "collection branch") || g(row, "collection branch public name") || g(row, "collection driver zone") || "";
    const client = (clientMap && clientMap[accCode]) || rawClient || accCode;
    if (accCode && !seenAccounts.has(accCode)) {
      seenAccounts.set(accCode, client);
    }
    const cSub = g(row, "collection suburb");
    const dSub = g(row, "delivery suburb");
    const cCity = g(row, "collection city") || g(row, "collection town") || "";
    const dCity = g(row, "delivery city") || g(row, "delivery town") || "";
    const cPostal = g(row, "collection postal code") || g(row, "collection postcode") || g(row, "collection zip") || "";
    const dPostal = g(row, "delivery postal code") || g(row, "delivery postcode") || g(row, "delivery zip") || "";
    const cAddr = g(row, "collection address");
    const dAddr = g(row, "delivery address");
    const cAfter = g(row, "collection after");
    const cBefore = g(row, "collection before");
    const dAfter = g(row, "delivery after");
    const dBefore = g(row, "delivery before");
    const cContact = g(row, "collection contact");
    const cPhone = g(row, "collection contact mobile no.");
    const cEmail = g(row, "collection contact email");
    const dContact = g(row, "delivery contact");
    const dPhone = g(row, "delivery contact mobile no.");
    const dEmail = g(row, "delivery contact email");
    const pcs = parseInt(g(row, "num parcels")) || 1;
    const kg = parseFloat(g(row, "charged weight")) || 1;
    const svc = g(row, "service level") || "STD";
    const rate = parseFloat(g(row, "rate")) || 0;
    const iCol = g(row, "special collection instructions");
    const iDel = g(row, "special delivery instructions");
    const colDriver = g(row, "collection driver");
    const delDriver = g(row, "delivery driver");
    const delZone = g(row, "delivery driver zone") || g(row, "delivery branch") || "";
    const tags = g(row, "tags");
    const trackUrl = g(row, "tracking url");
    const status = g(row, "status");
    const clientName = g(row, "client name") || g(row, "collection branch public name") || g(row, "account name") || rawClient || "";

    const eColDate = (g(row, "earliest collection date") || g(row, "collection date")).slice(0, 10) || "";
    const eDelDate = (g(row, "earliest delivery date") || g(row, "delivery date")).slice(0, 10) || "";
    const lDelDate = (g(row, "latest delivery date")).slice(0, 10) || "";
    const created = (g(row, "time created") || g(row, "date created")).slice(0, 10) || "";

    const csvCLat = gNum(row,
      "collection latitude", "collection lat", "col latitude", "col lat",
      "collection_latitude", "collection_lat", "col_latitude", "col_lat",
      "coll latitude", "coll lat", "collect lat", "collect latitude",
      "from latitude", "from lat", "from_lat", "origin latitude", "origin lat",
      "sender latitude", "sender lat"
    );
    const csvCLng = gNum(row,
      "collection longitude", "collection lng", "collection lon", "collection long",
      "col longitude", "col lng", "col lon", "col long",
      "collection_longitude", "collection_lng", "col_longitude", "col_lng",
      "coll longitude", "coll lng", "collect lng", "collect longitude",
      "from longitude", "from lng", "from_lng", "from long", "origin longitude", "origin lng",
      "sender longitude", "sender lng"
    );
    const csvDLat = gNum(row,
      "delivery latitude", "delivery lat", "del latitude", "del lat",
      "delivery_latitude", "delivery_lat", "del_latitude", "del_lat",
      "deliv latitude", "deliv lat", "deliver lat", "deliver latitude",
      "to latitude", "to lat", "to_lat", "destination latitude", "destination lat",
      "recipient latitude", "recipient lat"
    );
    const csvDLng = gNum(row,
      "delivery longitude", "delivery lng", "delivery lon", "delivery long",
      "del longitude", "del lng", "del lon", "del long",
      "delivery_longitude", "delivery_lng", "del_longitude", "del_lng",
      "deliv longitude", "deliv lng", "deliver lng", "deliver longitude",
      "to longitude", "to lng", "to_lng", "to long", "destination longitude", "destination lng",
      "recipient longitude", "recipient lng"
    );

    const csvCCoordValid = isValidSACoord(csvCLat, csvCLng);
    const csvDCoordValid = isValidSACoord(csvDLat, csvDLng);

    if (csvCLat !== null && csvCLng !== null && !csvCCoordValid) {
      warnings.push(wb + ": Collection GPS (" + csvCLat + ", " + csvCLng + ") is outside South Africa — ignored");
    }
    if (csvDLat !== null && csvDLng !== null && !csvDCoordValid) {
      warnings.push(wb + ": Delivery GPS (" + csvDLat + ", " + csvDLng + ") is outside South Africa — ignored");
    }

    const cGeo = csvCCoordValid
      ? { lat: csvCLat!, lng: csvCLng! }
      : geoLookup(cSub, cCity, cPostal);
    const dGeo = csvDCoordValid
      ? { lat: csvDLat!, lng: csvDLng! }
      : geoLookup(dSub, dCity, dPostal);

    const driverMap = getDriverMap();
    const preColDriver = driverMap[(colDriver || "").toLowerCase()] || "";
    const preDelDriver = driverMap[(delDriver || "").toLowerCase()] || "";

    const shipIdx = ships.length;
    wbMap.set(wb, { shipIdx, parcelCount: 1 });

    ships.push({
      id: wb.replace(/[^A-Z0-9]/gi, "").slice(0, 6) + String(r),
      wb, acc: accCode, client, pcs, kg, svc: svc.toUpperCase(), rate, perish: true,
      cSub, cCity, cPostal, cAddr, cAfter, cBefore, cLat: cGeo ? cGeo.lat : 0, cLng: cGeo ? cGeo.lng : 0,
      cContact, cPhone, cEmail, iCol,
      dSub, dCity, dPostal, dAddr, dAfter, dBefore, dLat: dGeo ? dGeo.lat : 0, dLng: dGeo ? dGeo.lng : 0,
      dContact, dPhone, dEmail, iDel,
      zone: delZone, tags, trackUrl, status,
      colDate: eColDate, delDate: eDelDate, lDelDate, created,
      preColDriver, preDelDriver,
      parcelType, parcelCategory, clientName,
      source: "csv", webhookEvents: [],
    });
  }

  const accountCodes = Array.from(seenAccounts.entries()).map(([code, name]) => ({ code, name }));
  return { ships, warnings, raw, headers: hdr, accountCodes };
}
