# Generated by Django 5.2.15 on 2026-06-20 20:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('default_length_cm', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('default_width_cm', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('default_height_cm', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('default_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParcelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('perishable', models.BooleanField(default=False)),
                ('fragile', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Parcel categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
