# Generated by Django 5.2.15 on 2026-06-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_booking_custom_tracking_ref_and_more'),
        ('quotes', '0012_alter_clientquotelink_collection_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('portal', 'Booked in portal'), ('api', 'Created via website API'), ('woocommerce', 'WooCommerce store'), ('shopify', 'Shopify store')], default='portal', max_length=20)),
                ('source_store', models.CharField(blank=True, max_length=120)),
                ('consignment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('custom_tracking_reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('customer_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status_raw', models.CharField(blank=True, max_length=60)),
                ('stage', models.CharField(choices=[('created', 'Created'), ('collected', 'Collected'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], db_index=True, default='created', max_length=20)),
                ('courier_service', models.CharField(blank=True, max_length=40)),
                ('shipping_cost_cents', models.BigIntegerField(default=0)),
                ('collection_summary', models.CharField(blank=True, max_length=255)),
                ('delivery_summary', models.CharField(blank=True, max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('estimated_collection', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('driver_lat', models.FloatField(blank=True, null=True)),
                ('driver_lng', models.FloatField(blank=True, null=True)),
                ('driver_eta', models.DateTimeField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_record', to='finance.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='quotes.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(max_length=60)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.shipment')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['client', 'stage', 'created_at'], name='tracking_sh_client__ed23ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackingevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('shipment', 'external_id'), name='uniq_event_per_shipment_external'),
        ),
    ]
