# Generated by Django 5.2.15 on 2026-06-20 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0012_alter_clientquotelink_collection_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('rejected_insufficient_funds', 'Rejected: insufficient funds'), ('charged', 'Charged'), ('dispatched', 'Dispatched to ShipLogic'), ('reversed', 'Reversed / cancelled')], db_index=True, max_length=40)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('collection', models.JSONField(blank=True, default=dict)),
                ('delivery', models.JSONField(blank=True, default=dict)),
                ('parcels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='quotes.client')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='quotes.quote')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('engine.event', 'Push event to financial engine'), ('shiplogic.shipment', 'Create shipment in ShipLogic'), ('shiplogic.billing', 'Post billing transaction in ShipLogic')], db_index=True, max_length=40)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed (dead-letter, manual reattempt)')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=12)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['next_attempt_at', 'id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='finance_out_status_c04ba9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=160)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_inbound_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='ShipLogicShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiplogic_id', models.CharField(blank=True, max_length=64)),
                ('waybill', models.CharField(blank=True, db_index=True, max_length=64)),
                ('service_level_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='finance.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('provider', models.CharField(default='bobpay', max_length=40)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topups', to='quotes.client')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_cents', models.BigIntegerField(default=0)),
                ('engine_account_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('shiplogic_account_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='quotes.client')),
            ],
        ),
        migrations.CreateModel(
            name='ShipLogicBillingTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('admin-debit', 'admin-debit'), ('admin-credit', 'admin-credit'), ('payment', 'payment')], max_length=16)),
                ('amount_cents', models.BigIntegerField()),
                ('account_id', models.CharField(max_length=64)),
                ('shiplogic_reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_txns', to='finance.booking')),
                ('topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_txns', to='finance.topup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking', 'kind'), name='uniq_billing_per_booking_kind')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Top-up'), ('booking_charge', 'Booking charge'), ('booking_reversal', 'Booking reversal'), ('adjustment', 'Manual adjustment')], max_length=32)),
                ('amount_cents', models.BigIntegerField(help_text='Signed. Credit > 0, debit < 0.')),
                ('balance_after_cents', models.BigIntegerField()),
                ('reference', models.CharField(db_index=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.wallet')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['wallet', 'id'], name='finance_led_wallet__b15af5_idx')],
            },
        ),
    ]
