# Generated by Django 5.2.15 on 2026-06-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.deliveryslot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('rejected_insufficient_funds', 'Rejected: insufficient funds'), ('rejected_slot_unavailable', 'Rejected: slot unavailable'), ('charged', 'Charged'), ('dispatched', 'Dispatched to ShipLogic'), ('reversed', 'Reversed / cancelled')], db_index=True, max_length=40),
        ),
    ]
