# Generated by Django 5.2.15 on 2026-06-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('finance', '0002_booking_slot_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_tracking_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='declared_value_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='liability_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='route_planner_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='shiplogic_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='waybill',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1)),
                ('length_cm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('width_cm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('height_cm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('alt_tracking_ref', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_items', to='finance.booking')),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='catalog.packagetype')),
                ('parcel_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='catalog.parcelcategory')),
            ],
            options={
                'ordering': ['booking', 'index'],
            },
        ),
        migrations.CreateModel(
            name='BookingIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('value', models.CharField(db_index=True, max_length=160)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='finance.booking')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('value',), name='uniq_identifier_value')],
            },
        ),
    ]
