# Generated by Django 5.2.15 on 2026-06-21 09:04

import backend.finance.treasury.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_booking_custom_tracking_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('cost', 'Variable cost (fuel, driver)'), ('operating_expense', 'Fixed operating expense'), ('reserve', 'Reserve'), ('capital', 'Capital / retained earnings')], max_length=20)),
                ('balance_cents', models.BigIntegerField(default=0)),
                ('priority', models.IntegerField(default=100, help_text='Lower funds first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_bps', models.IntegerField(default=0, help_text='Basis points of contribution margin. 10000 = 100%.')),
                ('priority', models.IntegerField(default=100)),
                ('basis', models.CharField(blank=True, max_length=255)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='finance.allocationwallet')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=80)),
                ('amount_cents', models.BigIntegerField()),
                ('due_day', models.IntegerField(default=1, help_text='Day of month the debit order runs (1-31).')),
                ('recurrence', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=12)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obligation', to='finance.allocationwallet')),
            ],
            options={
                'ordering': ['priority', 'due_day'],
            },
        ),
        migrations.CreateModel(
            name='FundingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_cents', models.BigIntegerField(default=0)),
                ('cadence', models.CharField(default='monthly', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_target', to='finance.allocationwallet')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField(help_text='Signed. Credit to wallet > 0, reversal < 0.')),
                ('kind', models.CharField(choices=[('cost_fuel', 'Fuel cost'), ('cost_driver', 'Driver payout'), ('allocation', 'Expense allocation'), ('overflow', 'Reserve / retained overflow'), ('reversal', 'Reversal')], max_length=16)),
                ('period', models.CharField(db_index=True, default=backend.finance.treasury.models.current_period, max_length=7)),
                ('source', models.CharField(default='contribution_margin', max_length=40)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_txns', to='finance.booking')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.allocationwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'period'], name='finance_all_wallet__38d03f_idx')],
            },
        ),
    ]
