"""Revenue intelligence, the dynamic recommender, and the treasury forecast.
Functions take explicit inputs where possible so they are testable in isolation."""
import csv
import datetime as dt
import statistics

from django.utils import timezone

from .models import AllocationWallet, AllocationRule, current_period
from .services import compute_costs


def revenue_analytics(revenues_cents, span_days):
    """Summary stats over a list of per-booking revenues (cents) and the calendar
    span they cover. Contribution margin uses the configured cost rates."""
    n = len(revenues_cents)
    total = sum(revenues_cents)
    span_days = max(1, span_days)
    avg_booking = total / n if n else 0
    per_day = total / span_days
    per_month = per_day * 30.4
    cm_total = sum(compute_costs(r)['contribution_margin_cents'] for r in revenues_cents)
    cm_rate = (cm_total / total) if total else 0
    return {
        'bookings': n, 'total_revenue_cents': total,
        'avg_booking_cents': int(avg_booking),
        'revenue_per_day_cents': int(per_day),
        'revenue_per_week_cents': int(per_day * 7),
        'revenue_per_month_cents': int(per_month),
        'contribution_margin_cents': cm_total,
        'contribution_margin_rate': round(cm_rate, 4),
        'monthly_contribution_margin_cents': int(per_month * cm_rate),
        'span_days': span_days,
    }


def revenues_from_csv(path):
    """Read per-booking revenue (the Rate column) from a ShipLogic export. The
    first physical line is a 'Generated by' banner; the header is the second."""
    lines = open(path, encoding='utf-8').read().splitlines()
    rows = list(csv.DictReader(lines[1:]))
    revs, dates = [], []
    for r in rows:
        try:
            revs.append(int(round(float((r.get('Rate') or '0').replace(',', '')) * 100)))
        except ValueError:
            continue
        d = (r.get('Booked date') or r.get('Time created') or '')[:10]
        try:
            dates.append(dt.date.fromisoformat(d))
        except ValueError:
            pass
    span = (max(dates) - min(dates)).days + 1 if dates else len(revs)
    return revs, span


def analytics_from_bookings():
    """Live analytics from charged/dispatched bookings already in the system."""
    from ..models import Booking
    qs = Booking.objects.filter(status__in=('charged', 'dispatched'))
    revs = list(qs.values_list('price_cents', flat=True))
    dates = list(qs.values_list('created_at', flat=True))
    span = (max(dates) - min(dates)).days + 1 if dates else max(1, len(revs))
    return revenue_analytics(revs, span)


def recommend_rules(monthly_cm_cents):
    """Derive each wallet's recommended share of contribution margin from its
    obligation and the historical monthly margin. Never hardcoded: if margin is
    scarce the obligations split 100% by weight; if ample, the remainder is
    earmarked to reserves. Writes AllocationRule rows and returns the plan."""
    exp = list(AllocationWallet.objects.filter(category='operating_expense', is_active=True))
    targets = {w: w.target_cents() for w in exp}
    total_oblig = sum(targets.values()) or 1
    now = timezone.now()
    plan = []

    if monthly_cm_cents <= 0:
        shares = {w: 0 for w in exp}
    elif monthly_cm_cents >= total_oblig:
        # Ample: each obligation needs target/monthly_cm of margin; rest to reserves.
        shares = {w: targets[w] / monthly_cm_cents for w in exp}
    else:
        # Scarce (today's reality): split all margin by obligation weight.
        shares = {w: targets[w] / total_oblig for w in exp}

    for w in exp:
        bps = int(round(shares[w] * 10000))
        AllocationRule.objects.update_or_create(
            wallet=w, defaults={'percent_bps': bps, 'priority': w.priority,
                                'basis': f"target {targets[w]}c vs monthly CM {monthly_cm_cents}c",
                                'computed_at': now})
        plan.append({'wallet': w.slug, 'percent_bps': bps,
                     'target_cents': targets[w]})
    covered = sum(min(targets[w], int(monthly_cm_cents * shares[w])) for w in exp)
    return {'monthly_cm_cents': monthly_cm_cents, 'total_obligations_cents': total_oblig,
            'coverage_ratio': round(monthly_cm_cents / total_oblig, 3),
            'expense_bps_total': sum(p['percent_bps'] for p in plan),
            'plan': plan}


def forecast(period=None, avg_daily_cm_cents=None):
    """Per-wallet funding progress, days-until-funded, and a month-end view."""
    period = period or current_period()
    if avg_daily_cm_cents is None:
        a = analytics_from_bookings()
        avg_daily_cm_cents = int(a['monthly_contribution_margin_cents'] / 30.4)
    today = timezone.now().date()
    import calendar
    days_in_month = calendar.monthrange(today.year, today.month)[1]
    days_left = days_in_month - today.day

    wallets = []
    total_target = total_funded = 0
    exp = AllocationWallet.objects.filter(category='operating_expense', is_active=True).order_by('priority')
    n_exp = exp.count() or 1
    per_wallet_daily = avg_daily_cm_cents / n_exp  # rough: margin spread across obligations
    for w in exp:
        target = w.target_cents()
        funded = w.funded_this_period(period)
        remaining = max(0, target - funded)
        total_target += target
        total_funded += funded
        days_to_fund = (remaining / per_wallet_daily) if per_wallet_daily > 0 and remaining > 0 else 0
        ob = getattr(w, 'obligation', None)
        wallets.append({
            'wallet': w.slug, 'name': w.name, 'target_cents': target,
            'funded_cents': funded, 'remaining_cents': remaining,
            'progress': round(funded / target, 3) if target else 1.0,
            'due_day': ob.due_day if ob else None,
            'days_until_funded': round(days_to_fund, 1),
            'funded': remaining == 0,
            'at_risk': bool(ob and remaining > 0 and (ob.due_day - today.day) % days_in_month < days_to_fund),
        })
    projected_month_end = total_funded + int(avg_daily_cm_cents * days_left)
    return {
        'period': period, 'today': today.isoformat(),
        'avg_daily_contribution_margin_cents': avg_daily_cm_cents,
        'total_obligations_cents': total_target,
        'funded_to_date_cents': total_funded,
        'projected_month_end_funding_cents': projected_month_end,
        'projected_coverage': round(projected_month_end / total_target, 3) if total_target else 1.0,
        'projected_shortfall_cents': max(0, total_target - projected_month_end),
        'wallets': wallets,
    }
