import "dotenv/config";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { db, pool } from "../db/client";

// Applies the SQL migrations in ./migrations (generated by `npm run db:generate`).
// For local/dev you can skip migrations entirely and use `npm run db:push`.
async function main() {
  console.log("Running migrations...");
  await migrate(db, { migrationsFolder: "./migrations" });
  console.log("Migrations complete.");
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
