# Generated by Django 6.0.5 on 2026-05-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_address', models.TextField()),
                ('bakery_address', models.TextField()),
                ('end_depot_address', models.TextField()),
                ('depot_to_bakery_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bakery_to_first_customer_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('distance_from_previous_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='quotes.quote')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
