# Generated by Django 6.0.5 on 2026-05-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_customer_coords_lat_customer_coords_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('vip', 'VIP')], default='active', max_length=20)),
                ('loyalty', models.BooleanField(default=False)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('quote_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('avatar_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True)),
                ('license_plate', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle'), ('bakkie', 'Bakkie')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('standby', 'Standby'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='quotes.driver')),
            ],
            options={
                'ordering': ['vehicle_id'],
            },
        ),
    ]
