# Generated by Django 6.0.5 on 2026-05-23 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_client_driver_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Delicate Courier Logistics', max_length=100)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='Africa/Johannesburg', max_length=50)),
                ('email_quotes', models.BooleanField(default=True)),
                ('sms_updates', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('min_delivery_fee', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=4.5, max_digits=5)),
                ('google_maps_key', models.CharField(blank=True, default='', max_length=100)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('allowed_ips', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('finance', 'Finance'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
