# Generated by Django 6.0.5 on 2026-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_sitesettings_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
