# Generated by Django 6.0.5 on 2026-05-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coords_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='coords_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
