# Generated by Django 6.0.6 on 2026-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_customer_coords_lat_alter_customer_coords_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='pickup_coords_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pickup_coords_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
