# Generated by Django 6.0.6 on 2026-06-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_customer_name_quote_early_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='delivery_directions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
