# Generated by Django 5.2.15 on 2026-06-13 13:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quote_delivery_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=Decimal('1.70'), max_digits=8)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('55.00'), help_text='Gross margin as a percentage. 55 means 55%.', max_digits=5)),
                ('fuel_surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Added on top of the base price, as a percentage. 0 = none.', max_digits=5)),
                ('min_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price floor. The quote never drops below this. 0 = no floor.', max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='The card used by the public quote generator and any link without an active card.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientQuoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text="Internal note, e.g. 'Honey Bee Baker daily quotes'.", max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Leave blank for a permanent link.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_links', to='quotes.client')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='quotes.ratecard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='client_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quotes.clientquotelink'),
        ),
        migrations.AddField(
            model_name='quote',
            name='rate_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quotes.ratecard'),
        ),
    ]
