# Generated by Django 5.2.15 on 2026-06-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_ratecard_clientquotelink_quote_client_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquotelink',
            name='collection_address',
            field=models.TextField(blank=True, help_text='Pre-set collection address. Leave blank to let the client enter it themselves.'),
        ),
        migrations.AddField(
            model_name='clientquotelink',
            name='collection_lat',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Auto-filled from the address on save; can be set manually.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientquotelink',
            name='collection_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientquotelink',
            name='collection_name',
            field=models.CharField(blank=True, default='Pickup', help_text='Label for the collection point, e.g. the bakery name.', max_length=120),
        ),
    ]
