# Generated by Django 5.2.15 on 2026-06-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_clientquotelink_collection_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquotelink',
            name='collection_lat',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Auto-filled from the address on save; can be set manually.', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='clientquotelink',
            name='collection_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
