#!/usr/bin/env bash
#
# Render an nginx vhost for one Delicate host and print it to stdout.
#
#   infra/scripts/nginx-vhost.sh driver.delicatecourier.co.za
#   infra/scripts/nginx-vhost.sh dev.delicatecourier.co.za --public   # allow search engines
#
# Ports come from infra/docker/.env when it exists, so the vhost and the stack cannot disagree
# about where the web app is listening — which is the kind of mismatch that produces a 502 and
# twenty minutes of reading the wrong logs.
#
# Install it, keeping `nginx -t` before the reload:
#
#   HOST=driver.delicatecourier.co.za
#   infra/scripts/nginx-vhost.sh "$HOST" | sudo tee "/etc/nginx/sites-available/$HOST" >/dev/null
#   sudo ln -sfn "/etc/nginx/sites-available/$HOST" "/etc/nginx/sites-enabled/$HOST"
#   sudo certbot certonly --webroot -w /var/www/html -d "$HOST"
#   sudo nginx -t && sudo systemctl reload nginx
#
# The certificate must exist before the reload: nginx will not start a vhost whose
# `ssl_certificate` file is missing, and on a shared box that takes every other site with it.

set -euo pipefail
cd "$(dirname "$0")/../.."

HOST="${1:-}"
PUBLIC=0
for arg in "${@:2}"; do
  case "$arg" in
    --public) PUBLIC=1 ;;
    *) echo "unknown option: $arg" >&2; exit 1 ;;
  esac
done

if [[ -z "$HOST" ]]; then
  echo "usage: $0 <hostname> [--public]" >&2
  exit 1
fi
# A typo here becomes a certificate request for a name that does not exist, so check the shape.
if [[ ! "$HOST" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]]; then
  echo "that does not look like a hostname: $HOST" >&2
  exit 1
fi

TEMPLATE="infra/docker/nginx-vhost.conf.template"
[[ -f "$TEMPLATE" ]] || { echo "missing $TEMPLATE" >&2; exit 1; }

ENV_FILE="infra/docker/.env"
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
fi
WEB_PORT="${WEB_BIND_PORT:-8090}"
API_PORT="${API_BIND_PORT:-8091}"

# nginx will not accept a session-cache zone name with dots in it.
SLUG="$(printf '%s' "$HOST" | tr -c 'a-zA-Z0-9' '_')"

# A host nobody has decided is public stays out of search results. Opt in deliberately: a dev
# or ops host indexed by Google is a mistake that is slow to undo.
if [[ "$PUBLIC" == "1" ]]; then
  ROBOTS="    # Indexed deliberately: this host was rendered with --public."
else
  ROBOTS='    # Not a public site; keep it out of search results.
    add_header X-Robots-Tag "noindex, nofollow" always;'
fi

python3 - "$TEMPLATE" "$HOST" "$SLUG" "$WEB_PORT" "$API_PORT" "$ROBOTS" <<'PY'
import sys

template, host, slug, web_port, api_port, robots = sys.argv[1:7]
raw = open(template, encoding="utf-8").read()

# The template's authoring notes are for whoever edits the template, not for the installed
# vhost. Drop everything up to the sentinel.
SENTINEL = "# ---8<--- rendered output begins below this line\n"
body = raw.split(SENTINEL, 1)[1] if SENTINEL in raw else raw

for token, value in (
    ("__HOST__", host),
    ("__SLUG__", slug),
    ("__WEB_PORT__", web_port),
    ("__API_PORT__", api_port),
    ("__ROBOTS__", robots),
):
    body = body.replace(token, value)

# A placeholder that survived would be installed as broken nginx and fail `nginx -t` for every
# site on the box, so refuse here where the message is about this script.
leftover = [line for line in body.splitlines() if "__" in line]
if leftover:
    sys.stderr.write("unrendered placeholders remain:\n  " + "\n  ".join(leftover) + "\n")
    sys.exit(1)

sys.stdout.write(
    f"# Generated by infra/scripts/nginx-vhost.sh for {host}. Do not edit here — edit\n"
    f"# infra/docker/nginx-vhost.conf.template and render it again, or the next deploy\n"
    f"# quietly undoes your change.\n"
    f"# web → 127.0.0.1:{web_port}   api → 127.0.0.1:{api_port}\n\n"
)
sys.stdout.write(body)
PY
