# Generated by Django 5.2.15 on 2026-06-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SlotPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('operating_weekdays', models.JSONField(default=list)),
                ('windows', models.JSONField(default=list)),
                ('default_capacity', models.PositiveIntegerField(default=20)),
                ('lead_time_minutes', models.PositiveIntegerField(default=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('window_key', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed_full', 'Closed: at capacity'), ('closed_manual', 'Closed: manually')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'status'], name='scheduling__date_a835b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'window_key'), name='uniq_slot_per_date_window')],
            },
        ),
    ]
